[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[rpc_endpoints]
monad_testnet = "${MONAD_RPC_URL}"

[etherscan]
monad_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet.monad.xyz/api" }
